---
title: Jonathan Yap
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hi@jonathanyap.com
description: Discovering insights, designing products, hacking prototype, building
  UI with code.
baseurl: 
url: http://jonathanyap.com
twitter_username: yapjonathan
github_username: yapjonathan
linkedin_username: yapjonathan12
dribbble_username: yapjonathan
markdown: kramdown
permalink: pretty
exclude:
- node_modules
- LICENSE
- package.json
- README.md
- Gemfile
- gulpfile.babel.js
- ".babelrc"
- ".gitignore"
- sass
- scss
